apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: mb-appset
spec:
  generators:
  - clusters: {} #Empty map
  template:
    metadata:
      name: "mb-appset"
      annotations:
        argocd.argoproj.io/manifest-generate-paths: ".;.."
    spec:
      project: default
      source:
        repoURL: https://github.com/mayankbatra123/argocd-helm-sample/
        targetRevision: main
        path: "sample-chart"
        helm:
          # Release name override (defaults to application name)
          releaseName: "mb-appset"
      destination:
        server: "https://kubernetes.default.svc"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 2
